# Generated by Django 4.2.6 on 2023-10-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbnr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_time', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tbnr.image')),
            ],
        ),
    ]
