# Generated by Django 4.2.6 on 2023-10-08 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbnr', '0003_expiringlink_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
