# Generated by Django 4.2.6 on 2023-10-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbnr', '0004_alter_expiringlink_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiringlink',
            name='expiration_time',
        ),
    ]
