# Generated by Django 4.2.6 on 2023-10-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbnr', '0005_remove_expiringlink_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringlink',
            name='expiration_time',
            field=models.IntegerField(default=300),
        ),
    ]
