# Generated by Django 4.2.6 on 2023-10-08 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tbnr', '0007_expiringlink_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringlink',
            name='unique_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
